export const USER_IN_LOADING = 'USER_IN_LOADING'

export const ADD_CARD = 'ADD_CARD'
export const CARDS_IN_LOADING = 'CARDS_IN_LOADING'
export const RECEIVE_CARDS = 'RECEIVE_CARDS'

// export const ADD_DECK = 'ADD_DECK'
export const DECKS_IN_LOADING = 'DECKS_IN_LOADING'
export const RECEIVE_DECKS = 'RECEIVE_DECKS'
export const SET_CURRENT_DECK = 'SET_CURRENT_DECK'

export const RECEIVE_NOTES = 'RECEIVE_NOTES'
export const SET_CURRENT_NOTE = 'SET_CURRENT_NOTE'
export const NOTES_IN_LOADING = 'NOTES_IN_LOADING'

export const ADD_TAG = 'ADD_TAG'
export const RECEIVE_TAGS = 'RECEIVE_TAGS'

export const SHOW_NAVIGATION = 'SHOW_NAVIGATION'
export const HIDE_NAVIGATION = 'HIDE_NAVIGATION'
export const ORDER_CARD_BY_ID = 'ORDER_CARD_BY_ID'
export const ORDER_CARD_BY_FRONT = 'ORDER_CARD_BY_FRONT'
export const ORDER_CARD_BY_BACK = 'ORDER_CARD_BY_BACK'
export const SHOW_CARD_NOTE = 'SHOW_CARD_NOTE'
export const HIDE_CARD_NOTE = 'HIDE_CARD_NOTE'
export const CARD_MODE_DUO = 'CARD_MODE_DUO'
export const CARD_MODE_FRONT = 'CARD_MODE_FRONT'
export const CARD_MODE_BACK = 'CARD_MODE_BACK'
