export const USER_IN_LOADING = 'USER_IN_LOADING'

export const ADD_CARD = 'ADD_CARD'
export const CARDS_IN_LOADING = 'CARDS_IN_LOADING'
export const RECEIVE_CARDS = 'RECEIVE_CARDS'

export const ADD_DECK = 'ADD_DECK'
export const DECKS_IN_LOADING = 'DECKS_IN_LOADING'
export const RECEIVE_DECKS = 'RECEIVE_DECKS'
export const SET_CURRENT_DECK = 'SET_CURRENT_DECK'

export const SHOW_NAVIGATION = 'SHOW_NAVIGATION'
export const HIDE_NAVIGATION = 'HIDE_NAVIGATION'
